### ISSUE TITLE
Error when creating RO-Crate from repository containing symlink

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#1033]
This file is a symlink in this repository:
https://github.com/EBI-Metagenomics/pipeline-v5/blob/master/tools/hmmer/hmmscan_tab_modification/hmmscan_tab.py

Error is:
```
An Errno::ENOENT occurred in workflows#ro_crate:
  No such file or directory @ rb_sysopen - /tmp/d20220611-31019-18r7cii/tools/hmmer/hmmscan_tab_modification/hmmscan_tab.py

  app/models/concerns/workflow_extraction.rb:215:in `block in ro_crate_zip'
  app/models/concerns/workflow_extraction.rb:196:in `block (2 levels) in ro_crate'
  lib/git/operations.rb:88:in `block in in_temp_dir'
  lib/git/operations.rb:86:in `in_temp_dir'
  app/models/concerns/workflow_extraction.rb:194:in `block in ro_crate'
  app/models/concerns/workflow_extraction.rb:209:in `tap'
  app/models/concerns/workflow_extraction.rb:209:in `ro_crate'
  app/models/concerns/workflow_extraction.rb:214:in `ro_crate_zip'
  app/controllers/workflows_controller.rb:253:in `ro_crate'
  app/controllers/application_controller.rb:47:in `block in with_current_user'
  app/models/user.rb:269:in `with_current_user'
  app/controllers/application_controller.rb:46:in `with_current_user'
```

**Comment by fbacall** [comment]
RO-Crate library issue:

ResearchObject/ro-crate-ruby#26
