### ISSUE TITLE
Request cancel publishing email fails to be sent

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#1539]
the template for it is missing 

```
Missing template mailer/publishing_request_cancellation with "mailer". Searched in:
  * "mailer"

/seek/vendor/bundle/ruby/3.1.0/gems/actionmailer-6.1.7.3/lib/action_mailer/base.rb:967:in `each_template'
/seek/vendor/bundle/ruby/3.1.0/gems/actionmailer-6.1.7.3/lib/action_mailer/base.rb:955:in `collect_responses_from_templates'
/seek/vendor/bundle/ruby/3.1.0/gems/actionmailer-6.1.7.3/lib/action_mailer/base.rb:933:in `collect_responses'
/seek/vendor/bundle/ruby/3.1.0/gems/actionmailer-6.1.7.3/lib/action_mailer/base.rb:841:in `mail'
/seek/app/models/mailer.rb:350:in `publish_notification'
/seek/app/models/mailer.rb:39:in `publishing_request_cancellation'
```

also needs a mailer unit test

**Comment by floradanna** [comment]
While testing gatekeeper functions: No message about "pending request" is shown to the gatekeeper when clicking My profile --> Assets awaiting approval
