### ISSUE TITLE
Rightfield error when uploading a spreadsheet

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#303]
Rightfield error while uploading Excel file

**Comment by alaninmcr** [comment]
See https://docs.google.com/document/d/1iE5SMh64In5ISLlrmRbt95jib-Bv6m-JIKhK0koCfF0/edit# for compatility list

**Comment by alaninmcr** [comment]
This happened again during the IBISBA workshop. Error is

An Exception occurred in background at 2020-09-09 10:24:48 UTC :

  0    [main] ERROR uk.org.rightfield.RightField  - Error attempting export
java.lang.IllegalStateException: Unexpected (org.apache.poi.hssf.record.UnknownRecord) while looking for DV Table insert pos
        at org.apache.poi.hssf.model.RecordOrderer.findDataValidationTableInsertPos(RecordOrderer.java:310)
        at org.apache.poi.hssf.model.RecordOrderer.findSheetInsertPos(RecordOrderer.java:98)
        at org.apache.poi.hssf.model.RecordOrderer.addNewSheetRecord(RecordOrderer.java:92)
        at org.apache.poi.hssf.model.InternalSheet.getOrCreateDataValidityTable(InternalSheet.java:1660)
        at org.apache.poi.hssf.usermodel.HSSFSheet.getDataValidations(HSSFSheet.java:430)
        at uk.ac.manchester.cs.owl.semspreadsheets.model.hssf.impl.SheetHSSFImpl.getValidationData(SheetHSSFImpl.java:251)
        at uk.ac.manchester.cs.owl.semspreadsheets.model.hssf.impl.SheetHSSFImpl.getValidations(SheetHSSFImpl.java:239)
        at uk.ac.manchester.cs.owl.semspreadsheets.model.OntologyTermValidationWorkbookParser.collectLiteralValidations(OntologyTermValidationWorkbookParser.java:78)
        at uk.ac.manchester.cs.owl.semspreadsheets.model.OntologyTermValidationWorkbookParser.readOntologyTermValidations(OntologyTermValidationWorkbookParser.java:47)
        at uk.ac.manchester.cs.owl.semspreadsheets.model.OntologyTermValidationManager.readValidationFromWorkbook(OntologyTermValidationManager.java:53)
        at uk.ac.manchester.cs.owl.semspreadsheets.model.WorkbookManager.loadWorkbook(WorkbookManager.java:202)
        at uk.ac.manchester.cs.owl.semspreadsheets.model.WorkbookManager.loadWorkbook(WorkbookManager.java:219)
        at uk.ac.manchester.cs.owl.semspreadsheets.export.AbstractExporter.<init>(AbstractExporter.java:63)
        at uk.ac.manchester.cs.owl.semspreadsheets.export.CSVExporter.<init>(CSVExporter.java:32)
        at uk.org.rightfield.RightField.export(RightField.java:95)
        at uk.org.rightfield.RightField.handleArguments(RightField.java:72)
        at uk.org.rightfield.RightField.<init>(RightField.java:51)
        at uk.org.rightfield.RightField.main(RightField.java:46)

  /seek/lib/rightfield/rightfield.rb:37:in `block in generate_rightfield_csv'

  -------------------------------
Backtrace:
-------------------------------

  /seek/lib/rightfield/rightfield.rb:37:in `block in generate_rightfield_csv'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/cache.rb:323:in `block in fetch'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/cache.rb:694:in `block in save_block_result_to_cache'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/cache.rb:663:in `block in instrument'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:170:in `instrument'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/cache.rb:663:in `instrument'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/cache.rb:693:in `save_block_result_to_cache'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/cache.rb:323:in `fetch'
  /seek/lib/rightfield/rightfield.rb:21:in `generate_rightfield_csv'
  /seek/lib/seek/templates/extract/rightfield_extractor.rb:14:in `initialize'
  /seek/app/models/data_file.rb:218:in `new'
  /seek/app/models/data_file.rb:218:in `populate_metadata_from_template'
  /seek/app/controllers/data_files_controller.rb:342:in `rightfield_extraction_ajax'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/abstract_controller/base.rb:194:in `process_action'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
  /seek/app/controllers/application_controller.rb:44:in `block in with_current_user'
  /seek/app/models/user.rb:266:in `with_current_user'
  /seek/app/controllers/application_controller.rb:43:in `with_current_user'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:136:in `run_callbacks'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `block in instrument'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `instrument'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
  /seek/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.4.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/abstract_controller/base.rb:134:in `process'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.4.3/lib/action_view/rendering.rb:32:in `process'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_controller/metal.rb:191:in `dispatch'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_controller/metal.rb:252:in `dispatch'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:35:in `each'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:35:in `serve'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/exception_notification-4.2.1/lib/exception_notification/rack.rb:32:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/exception_notification-4.2.1/lib/exception_notification/rack.rb:32:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/exception_notification-4.2.1/lib/exception_notification/rack.rb:32:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:147:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/deflater.rb:44:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
  /seek/vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/lograge-0.10.0/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  /seek/vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `block in call'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:28:in `tagged'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `tagged'
  /seek/vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/static.rb:127:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/engine.rb:524:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
  /seek/vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
  /seek/vendor/bundle/ruby/2.4.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/puma-4.3.5/lib/puma/configuration.rb:228:in `call'
  /seek/vendor/bundle/ruby/2.4.0/gems/puma-4.3.5/lib/puma/server.rb:713:in `handle_request'
  /seek/vendor/bundle/ruby/2.4.0/gems/puma-4.3.5/lib/puma/server.rb:472:in `process_client'
  /seek/vendor/bundle/ruby/2.4.0/gems/puma-4.3.5/lib/puma/server.rb:328:in `block in run'
  /seek/vendor/bundle/ruby/2.4.0/gems/puma-4.3.5/lib/puma/thread_pool.rb:134:in `block in spawn_thread'

-------------------------------
Data:
-------------------------------

  * data: {:user=>
    {:id=>14,
     :login=>"deweverh",
     :created_at=>Mon, 07 Sep 2020 13:01:03 UTC +00:00},
   :person=>
    {:id=>14,
     :name=>"Heleen De Wever",
     :email=>"heleen.dewever@vito.be",
     :created_at=>Mon, 07 Sep 2020 13:03:16 UTC +00:00},
   :site_host=>"https://sandbox8.fairdomhub.org",
   :message=>"Problem attempting to extract from RightField for content blob 97"}

**Comment by alaninmcr** [comment]
Not IBISBA specific
