### ISSUE TITLE
Failure to upload a file

### ISSUE THREAD

**Issue by alaninmcr** [seek4science/seek#427]
A user had problems uploading a data file. One error e-mail is attached.

**Comment by alaninmcr** [comment]
An ActionView::Template::Error occurred in data_files#provide_metadata:

  undefined method `title' for nil:NilClass
  app/helpers/policy_helper.rb:171:in `permission_title'


-------------------------------
Request:
-------------------------------

  * URL        : https://sandbox8.fairdomhub.org/data_files/provide_metadata
  * HTTP Method: GET
  * IP address : 155.253.15.237
  * Parameters : {"controller"=>"data_files", "action"=>"provide_metadata"}
  * Timestamp  : 2020-09-09 11:31:16 UTC
  * Server : da457c103185
  * Rails root : /seek
  * Process: 44

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"_csrf_token"=>"LBkDV8lCV29TdpTfpZ15mdom7nthCHEDxKcv5B+nwDg=",
   "user_id"=>19,
   "uploaded_content_blob_id"=>110,
   "processed_datafile"=>
    #<DataFile:0x00007f6d199e2928
     id: nil,
     contributor_id: 19,
     title: nil,
     description: nil,
     template_id: nil,
     last_used_at: nil,
     created_at: nil,
     updated_at: nil,
     version: 1,
     first_letter: nil,
     other_creators: nil,
     uuid: nil,
     policy_id: nil,
     doi: nil,
     license: nil,
     simulation_data: false,
     deleted_contributor: nil>,
   "processed_assay"=>
    #<Assay:0x00007f6d187cdb98
     id: nil,
     title: nil,
     description: nil,
     created_at: nil,
     updated_at: nil,
     study_id: nil,
     contributor_id: 19,
     first_letter: nil,
     assay_class_id: nil,
     uuid: nil,
     policy_id: nil,
     institution_id: nil,
     assay_type_uri: nil,
     technology_type_uri: nil,
     suggested_assay_type_id: nil,
     suggested_technology_type_id: nil,
     other_creators: nil,
     deleted_contributor: nil,
     position: nil>,
   "processing_warnings"=>
    #<Seek::Templates::Extract::Warnings:0x00007f6d188df5b8
     @warnings=#<Set: {}>>}

-------------------------------
Environment:
-------------------------------

  * GATEWAY_INTERFACE                                      : CGI/1.2
  * HTTP_ACCEPT                                            : text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
  * HTTP_ACCEPT_ENCODING                                   : gzip, deflate, br
  * HTTP_ACCEPT_LANGUAGE                                   : it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7
  * HTTP_CONNECTION                                        : close
  * HTTP_COOKIE                                            : _seek_session=12b3106186acd6d00e8a70ef12e35bad
  * HTTP_DNT                                               : 1
  * HTTP_HOST                                              : sandbox8.fairdomhub.org
  * HTTP_REFERER                                           : https://sandbox8.fairdomhub.org/data_files/create_content_blob
  * HTTP_SEC_FETCH_DEST                                    : document
  * HTTP_SEC_FETCH_MODE                                    : navigate
  * HTTP_SEC_FETCH_SITE                                    : same-origin
  * HTTP_UPGRADE_INSECURE_REQUESTS                         : 1
  * HTTP_USER_AGENT                                        : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
  * HTTP_VERSION                                           : HTTP/1.0
  * HTTP_X_FORWARDED_FOR                                   : 155.253.15.237, 192.168.99.1
  * HTTP_X_FORWARDED_PROTO                                 : https
  * HTTP_X_FORWARDED_SERVER                                : sandbox8.fairdomhub.org
  * HTTP_X_REAL_IP                                         : 192.168.99.1
  * ORIGINAL_FULLPATH                                      : /data_files/provide_metadata
  * ORIGINAL_SCRIPT_NAME                                   :
  * PATH_INFO                                              : /data_files/provide_metadata
  * QUERY_STRING                                           :
  * REMOTE_ADDR                                            : 127.0.0.1
  * REQUEST_METHOD                                         : GET
  * REQUEST_PATH                                           : /data_files/provide_metadata
  * REQUEST_URI                                            : /data_files/provide_metadata
  * ROUTES_47140452763700_SCRIPT_NAME                      :
  * SCRIPT_NAME                                            :
  * SERVER_NAME                                            : sandbox8.fairdomhub.org
  * SERVER_PORT                                            : 443
  * SERVER_PROTOCOL                                        : HTTP/1.1
  * SERVER_SOFTWARE                                        : puma 4.3.5 Mysterious Traveller
  * action_controller.instance                             : #<DataFilesController:0x00007f6d187d2120>
  * action_dispatch.authenticated_encrypted_cookie_salt    : authenticated encrypted cookie
  * action_dispatch.backtrace_cleaner                      : #<Rails::BacktraceCleaner:0x000055bf7bc26948>
  * action_dispatch.content_security_policy                :
  * action_dispatch.content_security_policy_nonce_generator:
  * action_dispatch.content_security_policy_report_only    : false
  * action_dispatch.cookies_digest                         :
  * action_dispatch.cookies_rotations                      : #<ActiveSupport::Messages::RotationConfiguration:0x000055bf75b8d280>
  * action_dispatch.cookies_serializer                     : json
  * action_dispatch.encrypted_cookie_cipher                :
  * action_dispatch.encrypted_cookie_salt                  : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt           : signed encrypted cookie
  * action_dispatch.http_auth_salt                         : http authentication
  * action_dispatch.key_generator                          : #<ActiveSupport::CachingKeyGenerator:0x000055bf7dcd01f8>
  * action_dispatch.logger                                 : #<ActiveSupport::Logger:0x000055bf7c006450>
  * action_dispatch.parameter_filter                       : [:password, "rack.request.form_vars", /^((?-mix:client_secret|code|authentication_token|access_token|refresh_token))$/]
  * action_dispatch.redirect_filter                        : []
  * action_dispatch.remote_ip                              : 155.253.15.237
  * action_dispatch.request.content_type                   :
  * action_dispatch.request.formats                        : [#<Mime::Type:0x000055bf75c363a8 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html", @hash=-2430008996133256145>]
  * action_dispatch.request.parameters                     : {"controller"=>"data_files", "action"=>"provide_metadata"}
  * action_dispatch.request.path_parameters                : {:controller=>"data_files", :action=>"provide_metadata"}
  * action_dispatch.request.query_parameters               : {}
  * action_dispatch.request.request_parameters             : {}
  * action_dispatch.request_id                             : f0db2244-c76a-46a7-b082-5d7051c229e7
  * action_dispatch.routes                                 : #<ActionDispatch::Routing::RouteSet:0x000055bf7be21068>
  * action_dispatch.secret_key_base                        : 68c78aaf676aa7682dc4e4a648c8e845651452bf98ddb414e06c4af38ef6b6abeb8bbb5cd6f27d231e21b58c0e9091e6841309e3583074ee4ea3401dba757de9
  * action_dispatch.secret_token                           :
  * action_dispatch.show_detailed_exceptions               : false
  * action_dispatch.show_exceptions                        : true
  * action_dispatch.signed_cookie_digest                   :
  * action_dispatch.signed_cookie_salt                     : signed cookie
  * action_dispatch.use_authenticated_cookie_encryption    : false
  * puma.config                                            : #<Puma::Configuration:0x000055bf7580c610>
  * puma.request_body_wait                                 : 0
  * puma.socket                                            : #<TCPSocket:0x00007f6d199e7928>
  * rack.after_reply                                       : []
  * rack.errors                                            : #<IO:0x000055bf74d017e8>
  * rack.hijack                                            : #<Puma::Client:0x00007f6d199e7900>
  * rack.hijack?                                           : true
  * rack.input                                             : #<Puma::NullIO:0x000055bf74ccfa18>
  * rack.multiprocess                                      : false
  * rack.multithread                                       : true
  * rack.request.cookie_hash                               : {"_seek_session"=>"12b3106186acd6d00e8a70ef12e35bad"}
  * rack.request.cookie_string                             : _seek_session=12b3106186acd6d00e8a70ef12e35bad
  * rack.request.query_hash                                : {}
  * rack.request.query_string                              :
  * rack.run_once                                          : false
  * rack.session                                           : #<ActionDispatch::Request::Session:0x00007f6d199e48e0>
  * rack.session.options                                   : #<ActionDispatch::Request::Session::Options:0x00007f6d199e4890>
  * rack.session.record                                    : #<ActiveRecord::SessionStore::Session:0x00007f6d199e3058>
  * rack.tempfiles                                         : []
  * rack.url_scheme                                        : https
  * rack.version                                           : [1, 3]

-------------------------------
Backtrace:
-------------------------------

  app/helpers/policy_helper.rb:171:in `permission_title'
  app/helpers/policy_helper.rb:126:in `block in policy_hash'
  app/helpers/policy_helper.rb:114:in `map'
  app/helpers/policy_helper.rb:114:in `policy_hash'
  app/helpers/policy_helper.rb:151:in `block in project_policies_json'
  app/helpers/policy_helper.rb:150:in `each'
  app/helpers/policy_helper.rb:150:in `project_policies_json'
  app/views/projects/_project_selector.html.erb:71:in `_app_views_projects__project_selector_html_erb___1139014964721358579_70053400891800'
  app/views/data_files/multi-steps/_basic_metadata.html.erb:20:in `_app_views_data_files_multi_steps__basic_metadata_html_erb__3352824213423626973_70053368369440'
  app/views/data_files/provide_metadata.html.erb:31:in `block in _app_views_data_files_provide_metadata_html_erb__2006696958395055577_70053400922460'
  app/views/data_files/provide_metadata.html.erb:23:in `_app_views_data_files_provide_metadata_html_erb__2006696958395055577_70053400922460'
  app/controllers/application_controller.rb:44:in `block in with_current_user'
  app/models/user.rb:266:in `with_current_user'
  app/controllers/application_controller.rb:43:in `with_current_user'

-------------------------------
Data:
-------------------------------

  * data: {:user=>
    {:id=>19,
     :login=>"Pedrazzini",
     :created_at=>Tue, 08 Sep 2020 16:33:14 UTC +00:00},
   :person=>
    {:id=>19,
     :name=>"Emanuela Pedrazzini",
     :email=>"emanuela.pedrazzini@ibba.cnr.it",
     :created_at=>Tue, 08 Sep 2020 16:35:42 UTC +00:00},
   :site_host=>"https://sandbox8.fairdomhub.org"}

**Comment by alaninmcr** [comment]
cannot reproduce
