### ISSUE TITLE
MessageLog not destroyed when Person is

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#487]
Causes:
```
An ActionView::Template::Error occurred in admin#project_creation_requests:

  undefined method `title' for nil:NilClass
  app/views/admin/project_creation_requests.html.erb:15:in `block in _app_views_admin_project_creation_requests_html_erb__178535810315209517_47380039014320'
  app/views/admin/project_creation_requests.html.erb:13:in `_app_views_admin_project_creation_requests_html_erb__178535810315209517_47380039014320'
  app/controllers/application_controller.rb:43:in `block in with_current_user'
  app/models/user.rb:266:in `with_current_user'
  app/controllers/application_controller.rb:42:in `with_current_user'
```

when trying to view project creation requests page

**Comment by stuzart** [comment]
part of #426
