### ISSUE TITLE
Timeout when pulling SEEK Publication API 

### ISSUE THREAD

**Issue by whomingbird** [seek4science/seek#507]
**Describe the bug:**
When HITS website wants to synchronize publications using seek api, it receives occasional timeout errors. 
The result is that some publications are not fetched.. 

**Suspect reason:**
 Server limits ? 

**Possible solution:** 
Provide API with time span filter: 
It is now possible to only retrieve a list of publications that have been updated in the past 24 hours instead of all publications (https://publications.h-its.org/publications.json).

**Comment by whomingbird** [comment]
i found the following error message in **production.log** which is related to the failed publication json request. 

```
I, [2021-02-02T09:54:28.849507 #51]  INFO -- : method=GET path=/publications/167.json format=json controller=PublicationsController action=show status=200 duration=169.72 view=60.56 db=82.87 time=20699921.01 user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
F, [2021-02-02T09:54:29.067858 #51] FATAL -- :
F, [2021-02-02T09:54:29.067999 #51] FATAL -- : ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
F, [2021-02-02T09:54:29.068060 #51] FATAL -- :
F, [2021-02-02T09:54:29.068143 #51] FATAL -- : vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
vendor/bundle/ruby/2.4.0/gems/lograge-0.10.0/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `block in call'
.....
```

The same error happened for another failed json request... 
```
I, [2021-01-20T08:00:26.738447 #51]  INFO -- : method=GET path=/publications/1167.json format=json controller=PublicationsController action=show status=200 duration=110.55 view=40.42 db=52.72 time=19569878.96 user_agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
F, [2021-01-20T08:00:26.792888 #51] FATAL -- :
F, [2021-01-20T08:00:26.792981 #51] FATAL -- : ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
F, [2021-01-20T08:00:26.793022 #51] FATAL -- :
F, [2021-01-20T08:00:26.793072 #51] FATAL -- : vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
vendor/bundle/ruby/2.4.0/gems/lograge-0.10.0/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `block in call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:28:in `tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `tagged'
vendor/bundle/ruby/2.4.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `call'
```
