### ISSUE TITLE
Exception when creating snapshot causes 500

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#678]
It tries to generate a UUID on a content blob that has been deleted.

Maybe skip deleting converted files if the content blob was never saved/written to disk?

Trace:
```
  lib/seek/uniquely_identifiable.rb:18:in `regenerate_uuid'
  lib/seek/uniquely_identifiable.rb:22:in `uuid'
  app/models/content_blob.rb:137:in `storage_filename'
  app/models/content_blob.rb:145:in `filepath'
  app/models/content_blob.rb:311:in `block in delete_converted_files'
  app/models/content_blob.rb:310:in `each'
  app/models/content_blob.rb:310:in `delete_converted_files'
  lib/seek/research_objects/acts_as_snapshottable.rb:48:in `rescue in create_snapshot'
  lib/seek/research_objects/acts_as_snapshottable.rb:45:in `create_snapshot'
  app/controllers/snapshots_controller.rb:17:in `create'
  app/controllers/application_controller.rb:43:in `block in with_current_user'
  app/models/user.rb:269:in `with_current_user'
  app/controllers/application_controller.rb:42:in `with_current_user'
```

**Comment by fbacall** [comment]
test

**Comment by fbacall** [comment]
test 123
