### ISSUE TITLE
error when trying to view an svg

### ISSUE THREAD

**Issue by stuzart** [seek4science/seek#753]
an error occurs when trying to convert and view an svg:

> A Magick::ImageMagickError occurred in content_blobs#download:
> 
>   non-conforming drawing primitive definition `fill' @ error/draw.c/RenderMVGContent/4301
>   (eval):2:in `resize'

may be specific to that particular svg ( https://testing.sysmo-db.org/sops/50/content_blobs/2594/download?disposition=inline&image_size=900 )

> (eval):2:in `resize'
>   lib/seek/acts_as_fleximage_extension.rb:23:in `block in resize_image'
>   lib/seek/acts_as_fleximage_extension.rb:21:in `resize_image'
>   lib/seek/content_blob_common.rb:130:in `handle_download'
>   app/controllers/content_blobs_controller.rb:95:in `block (2 levels) in download'
>   app/controllers/content_blobs_controller.rb:94:in `download'

**Comment by stuzart** [comment]
need double checking, might be fixed

**Comment by stuzart** [comment]
the issue seems to be with the convertion and rescaling to png. It goes through all the steps, as with other image types, a png is created, but the resulting png cannot be displayed. 

An alternative could be to display an svg in its own view and frame, and apply the HTTP headers that finn describes, hopefully reusing the file rendering from the git stuff
