### ISSUE TITLE
Better errors for non-publication DOIs

### ISSUE THREAD

**Issue by fbacall** [seek4science/seek#826]
If a user tries to register a DOI for something that is not a publication (e.g. a Dataset: https://doi.org/10.13003/83B2GP ), nothing happens in the UI, and there is a 500 in the background:
```
NoMethodError - undefined method `find' for nil:NilClass:
  app/models/publication.rb:435:in `fetch_pubmed_or_doi_result'
  app/models/publication.rb:162:in `extract_metadata'
  app/controllers/publications_controller.rb:315:in `get_data'
  app/controllers/publications_controller.rb:143:in `fetch_preview'
  app/controllers/application_controller.rb:44:in `block in with_current_user'
  app/models/user.rb:269:in `with_current_user'
  app/controllers/application_controller.rb:43:in `with_current_user'
  ```

**Comment by fbacall** [comment]
Can catch the new `DOI::RecordNotSupported` exception from the DOI query tool gem
